# Generated by Django 6.0 on 2025-12-25 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percent', models.PositiveIntegerField(verbose_name='Процент прохождения')),
                ('result', models.CharField(max_length=100, verbose_name='Результат')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Прогресс обучения',
                'verbose_name_plural': 'Прогресс обучения',
            },
        ),
    ]
