# Generated by Django 6.0 on 2025-12-25 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_enrollment'),
        ('progress', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('student', 'course')},
        ),
    ]
