# Generated by Django 6.0 on 2025-12-25 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специализация')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Опыт работы (лет)')),
                ('bio', models.TextField(verbose_name='Описание профиля')),
            ],
            options={
                'verbose_name': 'Наставник',
                'verbose_name_plural': 'Наставники',
            },
        ),
    ]
