# Generated by Django 6.0 on 2025-12-25 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('education_level', models.CharField(max_length=100, verbose_name='Уровень образования')),
                ('interests', models.TextField(blank=True, verbose_name='Интересы')),
                ('study_status', models.CharField(max_length=100, verbose_name='Статус обучения')),
            ],
            options={
                'verbose_name': 'Обучающийся',
                'verbose_name_plural': 'Обучающиеся',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('relation_degree', models.CharField(max_length=50, verbose_name='Степень родства')),
                ('students', models.ManyToManyField(related_name='parents', to='students.student', verbose_name='Дети')),
            ],
            options={
                'verbose_name': 'Родитель',
                'verbose_name_plural': 'Родители',
            },
        ),
    ]
