# Generated by Django 6.0 on 2026-03-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_stats_and_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, help_text='Например: bi-star-fill', max_length=50, verbose_name='Bootstrap-иконка (bi-*)'),
        ),
        migrations.AlterField(
            model_name='studentbadge',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата получения'),
        ),
    ]
