# Generated by Django 6.0.3 on 2026-03-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_course_mentors_schedule_description_schedule_mentor_and_more'),
        ('students', '0003_alter_badge_icon_alter_studentbadge_awarded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='education.course', verbose_name='Курс (если привязан к курсу)'),
        ),
    ]
