# Generated by Django 6.0.3 on 2026-04-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_badge_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='initial_password',
            field=models.CharField(blank=True, default='', help_text='Сохраняется при создании ребёнка родителем', max_length=100, verbose_name='Начальный пароль'),
        ),
    ]
