# Generated by Django 6.0 on 2026-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_course_image_coursereview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_hours',
            field=models.PositiveIntegerField(verbose_name='Кол-во уроков'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение, отображаемое на главной странице.', null=True, upload_to='static/courses/images/', verbose_name='Изображение курса'),
        ),
    ]
