# Generated by Django 6.0 on 2026-03-25 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_coursecategory_course_category'),
        ('students', '0003_alter_badge_icon_alter_studentbadge_awarded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('choice', 'Выбор из вариантов'), ('matching', 'Соотнесение'), ('text', 'Развёрнутый ответ')], default='choice', max_length=20, verbose_name='Тип вопроса')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='placement_test/images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PlacementTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тест на определение способностей',
                'verbose_name_plural': 'Тесты на определение способностей',
            },
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.CharField(max_length=300, verbose_name='Левый элемент')),
                ('right_text', models.CharField(max_length=300, verbose_name='Правый элемент')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='education.placementquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Пара соотнесения',
                'verbose_name_plural': 'Пары соотнесения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Вариант ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='education.placementquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='placementquestion',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education.placementtest', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='PlacementTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершён')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('current_question_index', models.PositiveIntegerField(default=0, verbose_name='Текущий вопрос (индекс)')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Баллы')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placement_sessions', to='students.student', verbose_name='Студент')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='education.placementtest', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Сессия теста',
                'verbose_name_plural': 'Сессии тестов',
            },
        ),
        migrations.CreateModel(
            name='PlacementAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, verbose_name='Текстовый ответ')),
                ('matching_answer', models.JSONField(blank=True, null=True, verbose_name='Ответ на соотнесение')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Правильно')),
                ('selected_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.choiceoption', verbose_name='Выбранный вариант')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.placementquestion', verbose_name='Вопрос')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='education.placementtestsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Ответ на тест',
                'verbose_name_plural': 'Ответы на тест',
                'unique_together': {('session', 'question')},
            },
        ),
    ]
