# Generated by Django 6.0 on 2026-03-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_placementquestion_placementtest_matchingpair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choiceoption',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='placementanswer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='placementanswer',
            name='text_answer',
        ),
        migrations.RemoveField(
            model_name='placementtestsession',
            name='score',
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Какую категорию усиливает этот вариант ответа', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_options', to='education.coursecategory', verbose_name='Категория склонности'),
        ),
        migrations.AddField(
            model_name='matchingpair',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matching_pairs', to='education.coursecategory', verbose_name='Категория склонности'),
        ),
        migrations.AddField(
            model_name='placementtestsession',
            name='category_scores',
            field=models.JSONField(default=dict, verbose_name='Баллы по категориям'),
        ),
        migrations.AlterField(
            model_name='placementquestion',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Выбор из вариантов'), ('matching', 'Соотнесение')], default='choice', max_length=20, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='placementtestsession',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Текущий вопрос'),
        ),
    ]
