# Generated by Django 6.0 on 2026-03-26 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_remove_choiceoption_is_correct_and_more'),
        ('students', '0003_alter_badge_icon_alter_studentbadge_awarded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('lesson_type', models.CharField(choices=[('theory_test', 'Теория + Тест'), ('test_only', 'Только тест')], default='theory_test', max_length=20, verbose_name='Тип урока')),
                ('color', models.CharField(choices=[('violet', '#7748FF'), ('blue', '#3B82F6'), ('green', '#22C55E'), ('orange', '#F97316'), ('pink', '#EC4899'), ('teal', '#14B8A6'), ('red', '#EF4444'), ('yellow', '#EAB308')], default='violet', max_length=20, verbose_name='Цвет')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='education.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('theory', 'Теория'), ('test', 'Тест')], default='theory', max_length=10, verbose_name='Тип')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Текст / вопрос')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/cards/', verbose_name='Изображение')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='education.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Карточка урока',
                'verbose_name_plural': 'Карточки урока',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CardChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Текст варианта')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='education.lessoncard', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('completed', 'Завершён')], default='not_started', max_length=20)),
                ('current_card_index', models.PositiveIntegerField(default=0)),
                ('correct_answers', models.PositiveIntegerField(default=0)),
                ('total_test_cards', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='education.lesson', verbose_name='Урок')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Прогресс по уроку',
                'verbose_name_plural': 'Прогресс по урокам',
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
