# Generated by Django 6.0 on 2026-03-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_lesson_lessoncard_cardchoice_lessonprogress'),
        ('students', '0003_alter_badge_icon_alter_studentbadge_awarded_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursereview',
            unique_together={('course', 'student')},
        ),
    ]
