# Generated by Django 6.0.3 on 2026-03-30 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_alter_coursereview_unique_together'),
        ('mentors', '0001_initial'),
        ('students', '0003_alter_badge_icon_alter_studentbadge_awarded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='courses', to='mentors.mentor', verbose_name='Наставники'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='mentors.mentor', verbose_name='Наставник'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='students.student', verbose_name='Ученики'),
        ),
    ]
