# Generated by Django 6.0.3 on 2026-03-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_course_mentors_schedule_description_schedule_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardchoice',
            name='match_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текст для соотнесения'),
        ),
        migrations.AlterField(
            model_name='lessoncard',
            name='card_type',
            field=models.CharField(choices=[('theory', 'Теория'), ('test', 'Тест'), ('matching', 'Соотнесение'), ('open_answer', 'Развёрнутый ответ')], default='theory', max_length=15, verbose_name='Тип'),
        ),
    ]
