# Generated by Django 6.0.3 on 2026-05-07 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_alter_lesson_order'),
        ('mentors', '0001_initial'),
        ('students', '0005_add_student_initial_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Изображение, отображаемое на главной странице.', null=True, upload_to='courses/images/', verbose_name='Изображение курса'),
        ),
        migrations.AlterField(
            model_name='lessoncard',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Не начат'), ('in_progress', 'В процессе'), ('pending_review', 'На проверке'), ('completed', 'Завершён')], default='not_started', max_length=20),
        ),
        migrations.AlterField(
            model_name='placementquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='placement/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='OpenAnswerSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_text', models.TextField(verbose_name='Ответ ученика')),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], default='pending', max_length=20, verbose_name='Статус')),
                ('mentor_comment', models.TextField(blank=True, verbose_name='Правильный ответ / комментарий ментора')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='education.lessoncard', verbose_name='Карточка')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_submissions', to='education.lesson', verbose_name='Урок')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to='mentors.mentor', verbose_name='Проверил')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_submissions', to='students.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Ответ на развёрнутый вопрос',
                'verbose_name_plural': 'Ответы на развёрнутые вопросы',
                'unique_together': {('student', 'card')},
            },
        ),
    ]
